# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: master

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependecies    
      run: npm install --force

    - name: Build the app  
      run: npm run build --if-present

    - name: Copy the build file
      run: sudo cp -r /home/ubuntu/Skr-News-master/_work/Skr-news/Skr-news/build/* /var/www/Skr-News-master/build

    - name: Restart the server
      run: pm2 restart Skr-News-master
